package com.bank.islamic.profitcalculationanddistribution;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Profit Calculation And Distribution
 *
 * Business Area:      Deposits and Investment Accounts
 * Business Domain:    Profit Management
 * Functional Pattern: Process
 * Asset Type:         Profit Distribution Run
 * Control Record:     Profit Distribution Run Procedure
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Profit Calculation And Distribution — BIAN Semantic API")
                .description("Service Domain 'Profit Calculation And Distribution' (Process pattern) "
                        + "operating on the 'Profit Distribution Run Procedure' control record.")
                .version("0.1.0"));
    }
}
